[tool.black]
line-length = 120
target-version = ['py37']
include = 'evap.*\.pyi?$'
extend-exclude = """\
    evap/staff/fixtures/excel_files_test_data\\.py|\
    .*/urls\\.py|\
    .*/migrations/.*\
"""
